<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Boonex Photos';

$aLangContent = array(
    '_bx_photos_caption_browse_by_day' => 'Browse photos by day',
	'_bx_photos' => 'Photos',
	'_bx_photos_access_denied' => 'Access denied',
	'_bx_photos_action_view_original' => 'View original',
	'_bx_photos_action_fave' => 'Add to Favorites',
	'_bx_photos_action_unfave' => 'Drop from Favorites',
	'_bx_photos_action_report' => 'Report',
	'_bx_photos_action_share' => 'Share',
	'_bx_photos_actions' => 'Actions',
	'_bx_photos_add' => 'Add photo',
	'_bx_photos_add_info' => '<a href="{0}">Click here</a> to add more.',
	'_bx_photos_add_objects' => 'Add photos',
	'_bx_photos_admin' => 'Administration',
	'_bx_photos_admin_activate' => 'Activate',
	'_bx_photos_admin_deactivate' => 'Deactivate',
	'_bx_photos_admin_delete' => 'Delete',
	'_bx_photos_admin_feature' => 'Make featured',
	'_bx_photos_admin_main' => 'Main',
	'_bx_photos_admin_settings' => 'Settings',
	'_bx_photos_admin_unfeature' => 'Make unfeatured',
	'_bx_photos_albums' => 'Photo Albums',
	'_bx_photos_albums_add' => 'Add album',
	'_bx_photos_albums_admin' => 'Albums administration',
	'_bx_photos_albums_disapproved' => 'My disapproved albums',
	'_bx_photos_albums_my' => 'My albums',
	'_bx_photos_albums_count_info' => 'You have {0} <a href="{1}">albums(s)</a>.',
    '_bx_photos_albums_add_info' => '<a href="{0}">Click here</a> to create a new album.',
    '_bx_photos_albums_latest' => 'Albums',
	'_bx_photos_album_add' => 'Add',
	'_bx_photos_album_add_objects' => 'Add photos',
	'_bx_photos_album_delete' => 'Delete',
	'_bx_photos_album_delete_confirm' => 'Confirm',
	'_bx_photos_album_delete_error' => '{0} file(s) were left',
	'_bx_photos_album_delete_success' => 'Album was deleted successfully',
	'_bx_photos_album_delete_warning' => 'Are you sure about deletion of entire album and all contents?',
	'_bx_photos_album_disapproved' => 'Disapproved',
	'_bx_photos_album_edit' => 'Edit album',
	'_bx_photos_album_info' => 'Album info',
	'_bx_photos_album_main' => 'Main',
	'_bx_photos_album_main_objects' => 'Main',
	'_bx_photos_album_manage' => 'Manage',
	'_bx_photos_album_manage_objects' => 'Manage photos',
	'_bx_photos_album_manage_objects_disapproved' => 'Disapproved',
	'_bx_photos_album_manage_objects_pending' => 'Pending',
	'_bx_photos_album_objects' => 'Photos of this album',
	'_bx_photos_album_organize' => 'Organize',
	'_bx_photos_album_organize_reverse' => 'Reverse',
	'_bx_photos_album_save_success' => 'Album info was saved successfully',
	'_bx_photos_album_view' => 'Allow viewing album to',
	'_bx_photos_alert_commented' => '{0} commented your photo',
	'_bx_photos_alert_rated' => 'File was rated',
	'_bx_photos_all' => 'All photos',
	'_bx_photos_any' => 'Any',
	'_bx_photos_approved' => 'Approved',
	'_bx_photos_bcaption_all' => 'All tags',
	'_bx_photos_browse' => 'Browse',
	'_bx_photos_browse_by_album' => 'Browse photos from album "{0}"',
	'_bx_photos_browse_by_tag' => 'Browse photos by tag "{0}"',
	'_bx_photos_browse_by_category' => 'Browse photos by category "{0}"',
	'_bx_photos_browse_by_owner' => 'Browse photos from {0}',
	'_bx_photos_browse_file' => 'Select photo',
    '_bx_photos_categories_all' => 'All categories',
	'_bx_photos_choose_uploader' => 'Choose uploader',
	'_bx_photos_close' => 'Close',
	'_bx_photos_comments' => 'Comments',
	'_bx_photos_count_info' => 'You have {0} <a href="{1}">photo(s)</a> in this album.',
	'_bx_photos_count_status_info' => 'You have {0} <a href="{1}">{2} photo(s)</a> in this album.',
	'_bx_photos_couple_photo_block' => 'Couple Photos',
	'_bx_photos_delete' => 'Photo was deleted',
	'_bx_photos_delete_from_album' => 'Delete from album',
	'_bx_photos_delete_error' => 'File deleting error',
	'_bx_photos_disapproved' => 'Disapproved',
	'_bx_photos_distribute' => 'Terms of condition for photos distribution',
	'_bx_photos_embed' => 'Embed',
	'_bx_photos_Embed' => 'Flickr photo link',
	'_bx_photos_Embed_example' => 'Example: http://www.flickr.com/photos/39193323@N07/3606466418/',
	'_bx_photos_fav_add' => 'File was added to favorite list',
	'_bx_photos_fav_remove' => 'File was removed from favorite list',
	'_bx_photos_favorited' => 'My favorite photos',
	'_bx_photos_featured' => 'Featured photos',
	'_bx_photos_file_not_found' => 'Photo not found',
	'_bx_photos_file_was_uploaded' => 'Your photo was uploaded (id:{0}) by {1}',
	'_bx_photos_forbidden' => 'Access is forbidden',
	'_bx_photos_home' => 'Photos home',
	'_bx_photos_i_have_the_right_to_distribute' => 'I have the right to distribute these photos',
	'_bx_photos_info' => 'File info',
	'_bx_photos_info_main' => 'Main photo info',
	'_bx_photos_latest' => 'Latest photos from this user',
	'_bx_photos_latest_file' => 'Latest featured photo',
	'_bx_photos_main' => 'Main',
	'_bx_photos_menu_pending' => 'Pending',
	'_bx_photos_menu_profile' => 'Photos',
	'_bx_photos_my' => 'My photos',
	'_bx_photos_msg_page_not_found' => 'Page not found',
	'_bx_photos_no_file_for_rate' => 'No files for rating',
	'_bx_photos_not_found' => 'File not found',
	'_bx_photos_organize_objects' => 'Organize',
	'_bx_photos_pending' => 'Pending',
	'_bx_photos_photo_block' => 'Profile Photos', 
	'_bx_photos_plural' => 'photos',
	'_bx_photos_preview' => 'Preview',
	'_bx_photos_previous_rated' => 'Previously rated',
    '_bx_photos_profile_album_name' => '{0}\'s photos',
	'_bx_photos_public' => 'Public photos',
	'_bx_photos_rate' => 'Rate',
	'_bx_photos_rate_header' => 'Rate',
	'_bx_photos_record' => 'Shoot',
	'_bx_photos_regular' => 'Regular',
	'_bx_photos_related' => 'Related photos',
	'_bx_photos_save_success' => 'File info was saved',
    '_bx_photos_sbs_main' => 'Photo Updates',
    '_bx_photos_sbs_comments' => 'New Photo Comments',
    '_bx_photos_sbs_rates' => 'New Photo Votes',
	'_bx_photos_set_as_avatar' => 'Set as Avatar',
	'_bx_photos_single' => 'photo',
	'_bx_photos_size' => 'Size',
	'_bx_photos_size_unit' => 'Kb',
	'_bx_photos_special' => 'Featured photos',
	'_bx_photos_spy_added' => '<a href="{profile_link}">{profile_nick}</a> added a new photo <a href="{entry_url}">{entry_caption}</a>',
	'_bx_photos_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">photo</a> was commented by <a href="{profile_link}">{profile_nick}</a>',
	'_bx_photos_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">photo</a> was rated by <a href="{profile_link}">{profile_nick}</a>',
	'_bx_photos_submit' => 'Submit',
	'_bx_photos_top' => 'Top photos',
	'_bx_photos_top_menu_albums' => 'Photo albums',
    '_bx_photos_top_menu_album' => 'Photo album',
	'_bx_photos_top_menu_all' => 'All photos',
	'_bx_photos_top_menu_calendar' => 'Calendar',
	'_bx_photos_top_menu_categories' => 'Categories',
	'_bx_photos_top_menu_category' => 'Category',
	'_bx_photos_top_menu_favorited' => 'My favorite photos',
	'_bx_photos_top_menu_featured' => 'Featured photos',
	'_bx_photos_top_menu_home' => 'Photos home',
	'_bx_photos_top_menu_item' => 'Photos',
	'_bx_photos_top_menu_popular' => 'Popular photos',
	'_bx_photos_top_menu_profile' => 'Profiles photos',
	'_bx_photos_top_menu_rate' => 'Rater',
	'_bx_photos_top_menu_search' => 'Search',
	'_bx_photos_top_menu_tags' => 'Tags',	
	'_bx_photos_top_menu_top' => 'Top photos',
	'_bx_photos_undefined' => 'Undefined',
	'_bx_photos_upl_err' => 'photo upload failed (failed to accept information)',
	'_bx_photos_upl_file_err' => 'photo upload failed (photo error)',
	'_bx_photos_upl_succ' => 'photo was uploaded successfully',
	'_bx_photos_upload' => 'Photos',
	'_bx_photos_val_descr_err' => 'Description can`t be empty',
	'_bx_photos_val_title_err' => 'Title can`t be empty',
	'_bx_photos_view' => 'View photo',
	'_bx_photos_view_alt_fav'  => 'Favorited',
	'_bx_photos_view_alt_view' => 'Viewed',
	'_bx_photos_flickr_key_not_exist' => 'You should add your Flickr API key to use this feature',
	'_bx_photos_emb_err' => 'Embedding photo failed',
	'_bx_photos_wall_added_new' => 'added new',
    '_bx_photos_wall_photo' => 'photo',
    '_bx_photos_wall_photo_private' => 'private photo',
    '_sbs_txt_title_bx_photos' => 'Photo subscriptions',
	'_mma_photos_add' => 'photos add',
	'_mma_photos_view' => 'photos view', 
	'_mma_photos_delete' => 'photos delete',
	'_mma_photos_download' => 'photos download',
	'_mma_photos_approve' => 'photos approve',
	'_mma_photos_edit' => 'photos edit',
);

?>
