<?php

/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$aLangContent = array(
    '_bx_ads_added_spy' => '<a href="{profile_link}">{profile_nick}</a> added a new Ad <a href="{ads_url}">{ads_caption}</a>',
    '_bx_ads_rated_spy' => '<a href="{profile_link}">{profile_nick}</a> rated Ad <a href="{ads_url}">{ads_caption}</a>',
    '_bx_ads_last_featured' => 'Latest featured ad',
    '_bx_ads_last_ads' => 'Last Ads',
    '_bx_ads_Ads' => 'Ads',
    '_bx_ads_Ad' => 'Ad',
    '_bx_ads_Buy_Now' => 'Buy Now',
    '_bx_ads_wholesale' => 'wholesale',
    '_bx_ads_BuyMsg1' => 'You have chosen the "Buy Now" option to purchase the item above. If you wish to proceed and make an immediate purchase of this item at the price listed below, please click the "Continue" button. This will close the auction allowing you and the seller to complete the transaction.',
    '_bx_ads_BuyDetails1' => 'Buy Now Amount Details:',
    '_bx_ads_BuyMsg2' => 'Your "Buy it Now" bid has been received. Please contact the seller to complete the transaction.',
    '_bx_ads_Unit' => 'Unit',
    '_bx_ads_Users_other_listing' => 'Other user\'s listings',
    '_bx_ads_Manage_ads' => 'Manage ads',
    '_bx_ads_Browse_All_Ads' => 'Browse All Ads',
    '_bx_ads_My_Ads' => 'My Ads',
    '_bx_ads_Categories' => 'Categories',
    '_bx_ads_Keywords' => 'Keywords',
    '_bx_ads_Posted_by' => 'Posted by',
    '_bx_ads_Details' => 'Details',
    '_bx_ads_Life_Time' => 'Life Time',
    '_bx_ads_Filtered_ads' => 'Filtered ads',
    '_bx_ads_Sub_Categories' => 'Sub Categories',
    '_bx_ads_Add' => 'Post ad',
    '_bx_ads_Description' => 'Description',
    '_bx_ads_CustomField1' => 'Custom Field 1',
    '_bx_ads_CustomField2' => 'Custom Field 2',
    '_bx_ads_Apply' => 'Apply',
    '_bx_ads_Activate' => 'Activate',
    '_bx_ads_Back' => 'Back',
    '_bx_ads_equal' => 'Equal',
    '_bx_ads_bigger' => 'Max',
    '_bx_ads_smaller' => 'Min',
    '_bx_ads_Warn_max_live_days' => 'Your ad will be active for {0} days',
    '_bx_ads_Warn_max_file_size' => 'File: {0} too large to upload.<br>',
    '_bx_ads_Ad_succ_added' => 'Ad successfully added',
    '_bx_ads_Ad_succ_deleted' => 'Ad successfully deleted',
    '_bx_ads_Ad_fail_delete' => 'Failed to Delete Ad',
    '_bx_ads_Moderating' => 'Moderating (new ads)',
    '_bx_ads_Ad_succ_updated' => 'Ad successfully updated',
    '_bx_ads_Filter' => 'Filter',
    '_bx_ads_Offer_Details' => 'Offer Details',
    '_bx_ads_Main_category_successfully_added' => 'Main category successfully added',
    '_bx_ads_Main_category_successfully_deleted' => 'Main category successfully deleted',
    '_bx_ads_Main_category_failed_add' => 'Failed to add Main category',
    '_bx_ads_Sub_category_successfully_added' => 'Sub category successfully added',
    '_bx_ads_Sub_category_failed_add' => 'Failed to add Sub category',
    '_bx_ads_Main_category_failed_delete' => 'Failed to delete Main category',
    '_bx_ads_Sub_category_successfully_delete' => 'Sub category successfully deleted',
    '_bx_ads_Sub_category_failed_deleted' => 'Failed to delete Sub category',
    '_bx_ads_All_ads' => 'All Ads',
    '_bx_ads_Ad_photos' => 'Ad photos',
    '_bx_ads_user_posted_ad_comment' => '{0} posted a comment to your Ad',
    '_bx_ads_user_bought_ad' => '{0} wishes to buy your Ad',
    '_bx_ads_Custom_Values' => 'Custom Values',
    '_bx_ads_Top_Rated' => 'Top Rated',
    '_bx_ads_Popular' => 'Popular',
    '_bx_ads_Calendar' => 'Calendar',
    '_bx_ads_Featured' => 'Featured',
    '_bx_ads_Under_Development' => 'Under Development',
    '_bx_ads_Ads_Home' => 'Ads Home',
    '_bx_ads_Feature_it' => 'Feature it',
    '_bx_ads_De-Feature_it' => 'De-Feature it',
    '_bx_ads_msg_access_denied' => 'Access Denied',
    '_bx_ads_pending_approval' => 'Pending Approval',
    '_bx_ads_Disapproved' => 'Disapproved',
    '_bx_ads_admin_box_desc' => '<div style="text-align: center;margin:10px;">You have {0} <a href="{1}">ads</a>. <a href="{2}">Click here</a> to add one.</div>',
    '_bx_ads_privacy_comment' => 'Allow posting comments to',
    '_bx_ads_privacy_rate' => 'Allow rate to',
    '_bx_ads_privacy_view' => 'Allow view to',
    '_bx_ads_Existed_images' => 'Existing images',
    '_bx_ads_Manage_categories_form' => 'Manage categories form',
    '_bx_ads_Administration' => 'Administration',
    '_bx_ads_Add_ad' => 'Add ad',
    '_bx_ads_Caption_error' => 'please specify caption from 3 to 255 characters',
    '_bx_ads_Text_error' => 'please specify post text from 3 to 65535 characters',
    '_bx_ads_RSS' => 'RSS',
    '_bx_ads_post_text' => 'Post text',
	'_bx_ads_sbs_main' => 'New updates in <b>{0}</b> ad',
	'_bx_ads_sbs_comments' => 'New Comments for <b>{0}</b> ad',
	'_bx_ads_sbs_rates' => 'New votes for <b>{0}</b> ad',
    '_bx_ads_caption_browse_by_day' => 'Browse Ads posts By Day: ',
    '_sbs_txt_title_bx_ads' => 'Ads subscriptions',
    '_mma_ads_view' => 'ads view',
    '_mma_ads_browse' => 'ads browse',
    '_mma_ads_search' => 'ads search',
    '_mma_ads_add' => 'ads add',
    '_mma_ads_edit_any_ad' => 'ads edit any ad',
    '_mma_ads_delete_any_ad' => 'ads delete any ad',
    '_mma_ads_approving' => 'ads approving',
    '_bx_ads_caption_city' => 'City',
    '_bx_ads_caption_country' => 'Country',
    '_bx_ads_err_city' => 'please fill in city name',
    '_bx_ads_err_country' => 'please specify country',
    '_bx_ads_add_main_category' => 'Add main category',
    '_bx_ads_you_have_purchased_an_item' => 'You have purchased an item',
    '_bx_ads_someone_wants_to_purchase' => 'Someone wants to purchase an item that you have offered for sale',
    '_bx_ads_title_error_desc' => 'Title should be {0} symbols max',
    '_bx_ads_description_error_desc' => 'Description should be {0} symbols max',
    '_bx_ads_custom_error_desc' => 'CustomFieldName{0} should be {1} symbols max',
    '_bx_ads_choose_custom_action' => 'Choose custom action',
    '_bx_ads_category_manager' => 'Category manager',
    '_bx_ads_add_subcategory' => 'Add subcategory',
    '_bx_ads_parent_category' => 'Parent category',
    '_bx_ads_root' => 'Root',
    '_bx_ads_search_results_by_tag' => 'Search results by tag',
    '_bx_ads_customFieldName1' => 'Custom field 1 name',
    '_bx_ads_customFieldName2' => 'Custom field 2 name',
	'_bx_ads_wall_added_new' => 'added new',
    '_bx_ads_wall_photo' => 'ad',
    '_bx_ads_category_warn' => 'please select category and subcategory',
);

?>