<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Boonex Sounds';

$aLangContent = array(
    '_bx_sounds_caption_browse_by_day' => 'Browse sounds by day',
	'_bx_sounds' => 'Sounds',
	'_bx_sounds_access_denied' => 'Access denied',
	'_bx_sounds_action_download' => 'Download',
	'_bx_sounds_action_fave' => 'Add to Favorites',
	'_bx_sounds_action_unfave' => 'Drop from Favorites',
	'_bx_sounds_action_report' => 'Report',
	'_bx_sounds_action_share' => 'Share',
	'_bx_sounds_actions' => 'Actions',
	'_bx_sounds_add' => 'Add Sound',
	'_bx_sounds_add_info' => '<a href="{0}">Click here</a> to add more.',
	'_bx_sounds_add_objects' => 'Add Sounds',
	'_bx_sounds_admin' => 'Administration',
	'_bx_sounds_admin_activate' => 'Activate',
	'_bx_sounds_admin_deactivate' => 'Deactivate',
	'_bx_sounds_admin_delete' => 'Delete',
	'_bx_sounds_admin_feature' => 'Make featured',
	'_bx_sounds_admin_main' => 'Main',
	'_bx_sounds_admin_settings' => 'Settings',
	'_bx_sounds_admin_unfeature' => 'Make unfeatured',
	'_bx_sounds_albums' => 'Sound Albums',
    '_bx_sounds_albums_admin' => 'Albums administration',
    '_bx_sounds_albums_disapproved' => 'My disapproved albums',
	'_bx_sounds_albums_add' => 'Add album',
    '_bx_sounds_albums_my' => 'My albums',
    '_bx_sounds_albums_count_info' => 'You have {0} <a href="{1}">albums(s)</a>.',
    '_bx_sounds_albums_add_info' => '<a href="{0}">Click here</a> to create new album.',
    '_bx_sounds_albums_latest' => 'Albums',
    '_bx_sounds_album_add' => 'Add',
	'_bx_sounds_album_add_objects' => 'Add sounds',
	'_bx_sounds_album_delete' => 'Delete album',
	'_bx_sounds_album_delete_confirm' => 'Confirm',
	'_bx_sounds_album_delete_error' => '{0} file(s) were left',
	'_bx_sounds_album_delete_success' => 'Album was deleted successfully',
	'_bx_sounds_album_delete_warning' => 'Are you sure about deletion of entire album and all contents?',
    '_bx_sounds_album_disapproved' => 'Disapproved',
	'_bx_sounds_album_edit' => 'Edit album',
	'_bx_sounds_album_info' => 'Album info',
    '_bx_sounds_album_main' => 'Main',
	'_bx_sounds_album_main_objects' => 'Main',
    '_bx_sounds_album_manage' => 'Manage',
	'_bx_sounds_album_manage_objects' => 'Manage sounds',
	'_bx_sounds_album_manage_objects_disapproved' => 'Disapproved',
	'_bx_sounds_album_manage_objects_failed' => 'Failed',
	'_bx_sounds_album_manage_objects_not_processed' => 'Not processed',
    '_bx_sounds_album_objects' => 'sounds of this album',
	'_bx_sounds_album_organize' => 'Organize',
	'_bx_sounds_album_organize_reverse' => 'Reverse',
	'_bx_sounds_album_organize_save' => 'Save changes',
	'_bx_sounds_album_save_success' => 'Album info was saved successfully',
	'_bx_sounds_album_view' => 'Allow viewing album to',
	'_bx_sounds_alert_commented' => '{0} commented your Sound',
	'_bx_sounds_alert_rated' => 'File was commented',
	'_bx_sounds_all' => 'All Sounds',
	'_bx_sounds_any' => 'Any',
	'_bx_sounds_approved' => 'Approved',
	'_bx_sounds_bcaption_all' => 'All tags',
	'_bx_sounds_browse' => 'Browse',
	'_bx_sounds_browse_by_album' => 'Browse sounds from album "{0}"',
	'_bx_sounds_browse_by_tag' => 'Browse sounds by tag "{0}"',
	'_bx_sounds_browse_by_category' => 'Browse sounds by category "{0}"',
	'_bx_sounds_browse_by_owner' => 'Browse sounds from {0}',
	'_bx_sounds_browse_file' => 'Select Sound',
    '_bx_sounds_categories_all' => 'All categories',
    '_bx_sounds_choose_uploader' => 'Choose uploader',
	'_bx_sounds_categories_all' => 'All categories',
	'_bx_sounds_close' => 'Close',
	'_bx_sounds_comments' => 'Comments',
	'_bx_sounds_count_info' => 'You have {0} <a href="{1}">sound(s)</a> in this album.',
	'_bx_sounds_count_status_info' => 'You have {0} <a href="{1}">{2} sound(s)</a> in this folder.',
	'_bx_sounds_couple_Sound_block' => 'Couple Sounds',
	'_bx_sounds_delete' => 'Sound was deleted',
	'_bx_sounds_delete_from_album' => 'Delete from album',
	'_bx_sounds_delete_error' => 'File deleting error',
	'_bx_sounds_disapproved' => 'Disapproved',
	'_bx_sounds_distribute' => 'Terms of condition for Sounds distribution',
	'_bx_sounds_fav_add' => 'File was added to favorite list',
	'_bx_sounds_fav_remove' => 'File was removed from favorite list',
	'_bx_sounds_favorited' => 'My favorite sounds',
	'_bx_sounds_featured' => 'Features Sounds',
	'_bx_sounds_file_not_found' => 'Sound not found',
	'_bx_sounds_no_file_for_rate' => 'No files for rating',
	'_bx_sounds_failed' => 'Failed',
	'_bx_sounds_file_was_uploaded' => 'Your Sound was uploaded (id:{0}) by {1}',
	'_bx_sounds_forbidden' => 'Access is forbidden',
	'_bx_sounds_home' => 'Sounds home',
	'_bx_sounds_i_have_the_right_to_distribute' => 'I have the right to distribute these Sounds',
	'_bx_sounds_info' => 'File info',
	'_bx_sounds_info_main' => 'Main Sound info',
	'_bx_sounds_latest' => 'Latest Sounds from this user',
	'_bx_sounds_latest_file' => 'Latest featured sound',
	'_bx_sounds_main' => 'Main',
	'_bx_sounds_menu_pending' => 'Pending',
	'_bx_sounds_menu_profile' => 'Sounds',
	'_bx_sounds_my' => 'My Sounds',
	'_bx_sounds_msg_page_not_found' => 'Page not found',
	'_bx_sounds_not_found' => 'File not found',
	'_bx_sounds_organize_objects' => 'Organize',
	'_bx_sounds_pending' => 'Pending',
	'_bx_sounds_plural' => 'Sounds',
	'_bx_sounds_preview' => 'Preview',
	'_bx_sounds_previous_rated' => 'Previously rated',
	'_bx_sounds_processing' => 'Processing',
	'_bx_sounds_profile_album_name' => '{0}\'s sounds',
	'_bx_sounds_public' => 'Public sounds',
	'_bx_sounds_rate' => 'Rate',
	'_bx_sounds_rate_header' => 'Rate',
	'_bx_sounds_record' => 'Record',
    '_bx_sounds_regular' => 'Regular',
	'_bx_sounds_related' => 'Related Sounds',
	'_bx_sounds_save_success' => 'File info was saved',
    '_bx_sounds_sbs_main' => 'Sounds Updates',
    '_bx_sounds_sbs_comments' => 'New Sound Comments',
    '_bx_sounds_sbs_rates' => 'New Sound Votes',
	'_bx_sounds_single' => 'Sound',
	'_bx_sounds_size' => 'Size',
	'_bx_sounds_size_unit' => 'Kb',
	'_bx_sounds_Sound_block' => 'Profile Sounds', 
	'_bx_sounds_special' => 'Featured Sounds',
    '_bx_sounds_spy_added' => '<a href="{profile_link}">{profile_nick}</a> added a new sound <a href="{entry_url}">{entry_caption}</a>',
    '_bx_sounds_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">sound</a> was commented by <a href="{profile_link}">{profile_nick}</a>',
    '_bx_sounds_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">sound</a> was rated by <a href="{profile_link}">{profile_nick}</a>',
	'_bx_sounds_submit' => 'Submit',
	'_bx_sounds_top' => 'Top Sounds',
	'_bx_sounds_top_menu_all' => 'All Sounds',
    '_bx_sounds_top_menu_album' => 'Sound album',
    '_bx_sounds_top_menu_albums' => 'Sound albums',
	'_bx_sounds_top_menu_calendar' => 'Calendar',
	'_bx_sounds_top_menu_categories' => 'Categories',
    '_bx_sounds_top_menu_category' => 'Category',
	'_bx_sounds_top_menu_favorited' => 'My favorite sounds',
	'_bx_sounds_top_menu_featured' => 'Featured Sounds',
	'_bx_sounds_top_menu_home' => 'Sounds home',
	'_bx_sounds_top_menu_item' => 'Sounds',
	'_bx_sounds_top_menu_popular' => 'Popular Sounds',
	'_bx_sounds_top_menu_profile' => 'Profiles Sounds',
    '_bx_sounds_top_menu_rate' => 'Rater',
	'_bx_sounds_top_menu_search' => 'Search',
	'_bx_sounds_top_menu_tags' => 'Tags',
	'_bx_sounds_top_menu_top' => 'Top Sounds',
	'_bx_sounds_undefined' => 'Undefined',
	'_bx_sounds_upl_err' => 'Sound upload failed (failed to accept information)',
	'_bx_sounds_upl_file_err' => 'Sound upload failed (Sound error)',
	'_bx_sounds_upl_succ' => 'Sound was uploaded successfully',
	'_bx_sounds_upload' => 'Sounds',
	'_bx_sounds_val_descr_err' => 'Description can`t be empty',
	'_bx_sounds_val_title_err' => 'Title can`t be empty',
	'_bx_sounds_view' => 'Play Sound',
	'_bx_sounds_view_alt_fav'  => 'Favorited',
	'_bx_sounds_view_alt_view' => 'Played',
	'_bx_sounds_wall_added_new' => 'added new',
    '_bx_sounds_wall_music' => 'sound',
    '_bx_sounds_wall_music_private' => 'private sound',
    '_sbs_txt_title_bx_sounds' => 'Sound subscriptions',
	'_mma_sounds_add' => 'sounds add',
	'_mma_sounds_view' => 'sounds play', 
	'_mma_sounds_delete' => 'sounds delete',
	'_mma_sounds_download' => 'sounds download',
	'_mma_sounds_approve' => 'sounds approve',
	'_mma_sounds_edit' => 'sounds edit',
	'_bx_sounds_profile_sounds' => 'Profile Sounds',
);

?>
