#!/bin/sh

ME="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
MEAT=$(dirname $ME)

msg () {
    echo -e  "\E[31;40m""\033[1m$1\033[0m"
}

isused () {
    if netstat -an | egrep ":$1 .*LISTEN" > /dev/null
    then
        return 0
    else
        return 1
    fi
}

getprocnamebyport () {
    procname=$(netstat -tlnp | grep ":$1 .*LISTEN" | awk '{print $7}' | awk -F '/' '{print $2}')
    msg "$procname is listening port $1"
}

killbyport () {
    getprocnamebyport $1
    if [ -n $procname ] ; then
        msg "we are going to kill $procname"
		kill -9 $(ps -ef | grep $procname | grep -v 'grep' | awk '{print $2}')
        #killall $procname && msg "$procname was killed"
        #recursive kill
        if isused $1 ; then
            killbyport $1
        fi
    fi
}

checkport () {
    if isused $1 ; then
        killbyport $1 
    fi
}

###################################################################################

#nginx 
startnginx () {
    checkport 80
    #
    msg "starting nginx..."
    nginxctl=$MEAT/nginx/sbin/nginx
    if [ -f $nginxctl  ] ; then
        ulimit -SHn 51200
        $nginxctl
    else
        msg "nginx controller not found!"
        exit
    fi
    #
    if isused 80  ; then
        msg "start nginx  successful!"
    else
        msg "start nginx failed!"
    fi
}

stopnginx() {
    killbyport 80
}

testnginx() {
    nginxctl=$MEAT/nginx/sbin/nginx
    [ -f $nginxctl ] && $nginxctl -t	
}
#

startmysql () {
    checkport 3306
    #
    msg "starting mysql..."
    mysqlctl=$MEAT/mysql/share/mysql/mysql.server
    if [ -f $mysqlctl ] ; then
         $mysqlctl start
    else 
        msg "mysql controller not found!"
        exit
    fi
    #
    if isused 3306 ; then
        msg "start mysql successful!"
    else
        msg "start mysql failed!"
    fi
}

stopmysql () {
    mysqlctl=$MEAT/mysql/share/mysql/mysql.server
    if [ -f $mysqlctl ] ; then
         $mysqlctl stop
    else 
        msg "mysql controller not found!"
        exit
    fi
}

#
#php fast cgi

startphp () {
    checkport 9000
    #
    msg "starting php fast cgi"
    phpfastcgictl=$MEAT/php/sbin/php-fpm
    if [ -f $phpfastcgictl ] ; then
        ulimit -SHn 51200
         $phpfastcgictl start
    else
        msg "php fastcgi controller not found!"
        exit
    fi
    #
    if isused 9000 ; then
        msg "start php fast cgi successful!"
    else
        msg "start php fast cgi failed!"
    fi
}

stopphp () {
    killbyport 9000
}

#proftpd

startproftpd () {
	checkport 21
	#
	msg "starting proftpd..."
    proftpdctl=$MEAT/proftpd/sbin/proftpd
    proftpdetc=$MEAT/proftpd/etc/proftpd.conf
	if [ -f $proftpdctl ] ; then
	    $proftpdctl -c $proftpdetc
    else
        msg "proftpd controller not found!"
        exit
    fi
	#
	if isused 21 ; then
		msg "start proftpd successful!"
	else
		msg "start proftpd failed!"
	fi
}

stopproftpd () {
	killbyport 21
}

################################################################################

case $1 in
    "start")
        startnginx
        startmysql
        startphp
		startproftpd
    ;;

    "stop")
		stopproftpd
        stopphp
        stopmysql
        stopnginx
    ;;

	"test")
		testnginx
	;;

    *)
        echo "Usage: $0 <action>"
        echo ""
        echo "  start        Start NMPP (Nginx, MySQL, PHP Fastcgi, ProFTPd)"
        echo "  stop         Stop NMPP (Nginx, MySQL, PHP Fastcgi, ProFTPd)"
        echo "  test         Test NMPP (Nginx, MySQL, PHP Fastcgi, ProFTPd)"
    ;;

esac
