#!/bin/sh
ME="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
MEPATH=$(dirname $ME)
BASEDIR='../..'
. $BASEDIR/config
. $BASEDIR/functions


rm -rf src/*

DEPOT=$BASEDIR/$DEPOT
#
for iterator in $(ls dep)
do
	pushd dep/$iterator > /dev/null
	[ -f process ] && ./process
	popd > /dev/null
done

#
pkgname='php'
extract $pkgname
getSrcdir $pkgname
#
msg "patching php...."
fpmfile=$DEPOT/fpm.diff.gz
if [ -f $fpmfile ] ; then
    gzip -cd  $fpmfile | patch -d $MEPATH/$srcdir -p1 > /dev/null 
fi
msg "patched"
#
prefix=$INSTDIR/$pkgname
freetype=$prefix
jpegdir=$prefix
pngdir=$prefix
xmldir=$prefix
zlibdir=$prefix
#
#test -d $prefix && rm -rf $prefix  
cmd="./configure  \
--prefix=$prefix \
--with-config-file-path=$prefix/etc \
--with-mysql=$INSTDIR/mysql  
--with-freetype-dir=$freetypedir \
--with-jpeg-dir=$jpegdir \
--with-png-dir=$pngdir \
--with-zlib-dir=$zlibdir \
--with-gd \
--with-libxml-dir=$xmldir \
--disable-debug \
--disable-rpath \
--enable-inline-optimization \
--enable-mbregex \
--enable-fastcgi \
--enable-force-cgi-redirect \
--enable-mbstring \
--with-iconv-dir \
--enable-fpm  
"
echo $cmd > .log
pushd $srcdir >/dev/null  
compile $cmd
#copy configure file
/bin/cp -f php.ini-dist $prefix/etc/php.ini
popd >/dev/null
msg "$pkgname make complete!!"
#
msg "config fpm"
if pushd $prefix/etc > /dev/null
then
    sedcmd="sed -i 's,<!--.*<value name=\"user\">nobody</value>.*-->,<value name=\"user\">$RUNWEBUSR</value>,' php-fpm.conf"
    eval $sedcmd
    sedcmd="sed -i 's,<!--.*<value name=\"group\">nogroup</value>.*-->,<value name=\"user\">$RUNWEBGRP</value>,' php-fpm.conf"
    eval $sedcmd
fi

msg "$pkgname all done!!"

