#!/bin/sh

BASEDIR='../../../..'
. $BASEDIR/config
. $BASEDIR/functions

DEPOT=$BASEDIR/$DEPOT

pkgname='zlib'
#
rm -rf src/*
extract $pkgname
#
getSrcdir $pkgname

prefix=$INSTDIR/php

cmd="
./configure --prefix=$prefix
"
echo $cmd > .log
pushd $srcdir > /dev/null
compile $cmd
popd > /dev/null
