<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Boonex Videos';

$aLangContent = array(
    '_bx_videos_caption_browse_by_day' => 'Browse videos by day',
	'_bx_videos' => 'Videos',
	'_bx_videos_access_denied' => 'Access denied',
	'_bx_videos_action_download' => 'Download',
	'_bx_videos_action_fave' => 'Add to Favorites',
	'_bx_videos_action_unfave' => 'Drop from Favorites',
	'_bx_videos_action_report' => 'Report',
	'_bx_videos_action_share' => 'Share',
	'_bx_videos_actions' => 'Actions',
	'_bx_videos_add' => 'Add Video',
	'_bx_videos_add_info' => '<a href="{0}">Click here</a> to add more.',
	'_bx_videos_add_objects' => 'Add Videos',
	'_bx_videos_admin' => 'Administration',
	'_bx_videos_admin_activate' => 'Activate',
	'_bx_videos_admin_deactivate' => 'Deactivate',
	'_bx_videos_admin_delete' => 'Delete',
	'_bx_videos_admin_feature' => 'Make featured',
	'_bx_videos_admin_main' => 'Main',
	'_bx_videos_admin_settings' => 'Settings',
	'_bx_videos_admin_unfeature' => 'Make unfeatured',
	'_bx_videos_albums' => 'Video Albums',
    '_bx_videos_albums_add' => 'Add album',
    '_bx_videos_albums_admin' => 'Albums administration',
    '_bx_videos_albums_disapproved' => 'My disapproved albums',
    '_bx_videos_albums_my' => 'My albums',
    '_bx_videos_albums_count_info' => 'You have {0} <a href="{1}">albums(s)</a>.',
    '_bx_videos_albums_add_info' => '<a href="{0}">Click here</a> to create new album.',
    '_bx_videos_albums_latest' => 'Albums',
    '_bx_videos_album_add' => 'Add',
	'_bx_videos_album_add_objects' => 'Add Videos',
	'_bx_videos_album_delete' => 'Delete album',
	'_bx_videos_album_delete_confirm' => 'Confirm',
	'_bx_videos_album_delete_error' => '{0} file(s) were left',
	'_bx_videos_album_delete_success' => 'Album was deleted successfully',
	'_bx_videos_album_delete_warning' => 'Are you sure about deletion of entire album and all contents?',
    '_bx_videos_album_disapproved' => 'Disapproved',
	'_bx_videos_album_edit' => 'Edit album',
	'_bx_videos_album_info' => 'Album info',
    '_bx_videos_album_main' => 'Main',
	'_bx_videos_album_main_objects' => 'Main',
    '_bx_videos_album_manage' => 'Manage',
    '_bx_videos_album_manage_objects' => 'Manage objects',
	'_bx_videos_album_manage_objects_disapproved' => 'Disapproved',
	'_bx_videos_album_manage_objects_failed' => 'Failed',
	'_bx_videos_album_manage_objects_not_processed' => 'Not processed',
    '_bx_videos_album_objects' => 'videos of this album',
	'_bx_videos_album_organize' => 'Organize',
	'_bx_videos_album_organize_reverse' => 'Reverse',
	'_bx_videos_album_organize_save' => 'Save changes',
	'_bx_videos_album_save_success' => 'Album info was saved successfully',
	'_bx_videos_album_view' => 'Allow viewing album to',
	'_bx_videos_alert_commented' => '{0} commented your Video',
	'_bx_videos_alert_rated' => 'File was commented',
	'_bx_videos_all' => 'All Videos',
	'_bx_videos_any' => 'Any',
	'_bx_videos_approved' => 'Approved',
	'_bx_videos_bcaption_all' => 'All Videos',
	'_bx_videos_browse' => 'Browse',
	'_bx_videos_browse_by_album' => 'Browse videos from album "{0}"',
	'_bx_videos_browse_by_tag' => 'Browse videos by tag "{0}"',
	'_bx_videos_browse_by_category' => 'Browse videos by category "{0}"',
	'_bx_videos_browse_by_owner' => 'Browse videos from {0}',
	'_bx_videos_browse_file' => 'Select Video',
    '_bx_videos_categories_all' => 'All categories',
    '_bx_videos_choose_uploader' => 'Choose uploader',
	'_bx_videos_categories_all' => 'All categories',
	'_bx_videos_close' => 'Close',
	'_bx_videos_comments' => 'Comments',
	'_bx_videos_count_info' => 'You have {0} <a href="{1}">video(s)</a> in this album.',
	'_bx_videos_count_status_info' => 'You have {0} <a href="{1}">{2} video(s)</a> in this album.',
	'_bx_videos_couple_Video_block' => 'Couple Videos',
	'_bx_videos_delete' => 'Video was deleted',
	'_bx_videos_delete_from_album' => 'Delete from album',
	'_bx_videos_delete_error' => 'File deleting error',
	'_bx_videos_disapproved' => 'Disapproved',
	'_bx_videos_distribute' => 'Terms of condition for Videos distribution',
	'_bx_videos_embed' => 'Embed',
	'_bx_videos_Embed' => 'Youtube Video link',
	'_bx_videos_Embed_example' => 'Example: http://www.youtube.com/watch?v=_AANZvYn5uk',
	'_bx_videos_failed' => 'Failed',
	'_bx_videos_fav_add' => 'File was added to favorite list',
	'_bx_videos_fav_remove' => 'File was removed from favorite list',
	'_bx_videos_featured' => 'Featured Videos',
	'_bx_videos_favorited' => 'My favorite videos',
	'_bx_videos_file_not_found' => 'Video not found',
	'_bx_videos_no_file_for_rate' => 'No files for rating',
	'_bx_videos_file_was_uploaded' => 'Your Video was added (id:{0}) by {1}',
	'_bx_videos_forbidden' => 'Access is forbidden',
	'_bx_videos_home' => 'Videos home',
	'_bx_videos_i_have_the_right_to_distribute' => 'I have the right to distribute these Videos',
	'_bx_videos_info' => 'File info',
	'_bx_videos_info_main' => 'Main Video info',
	'_bx_videos_latest' => 'Latest Videos from this user',
	'_bx_videos_latest_file' => 'Latest featured video',
    '_bx_videos_main' => 'Main',
	'_bx_videos_menu_manage' => 'Manage',
	'_bx_videos_menu_pending' => 'Pending',
	'_bx_videos_menu_profile' => 'Videos',
	'_bx_videos_my' => 'My Videos',
	'_bx_videos_msg_page_not_found' => 'Page not found',
	'_bx_videos_not_found' => 'File not found',
	'_bx_videos_organize_objects' => 'Organize',
	'_bx_videos_pending' => 'Pending',
	'_bx_videos_processing' => 'Processing',
	'_bx_videos_plural' => 'Videos',
	'_bx_videos_preview' => 'Preview',
	'_bx_videos_previous_rated' => 'Previously rated',
	'_bx_videos_profile_album_name' => '{0}\'s videos',
	'_bx_videos_public' => 'Public videos',
	'_bx_videos_rate' => 'Rate',
	'_bx_videos_record' => 'Record',
	'_bx_videos_rate_header' => 'Rate',
    '_bx_videos_regular' => 'Regular',
	'_bx_videos_related' => 'Related Videos',
	'_bx_videos_save_success' => 'File info was saved',
    '_bx_videos_sbs_main' => 'Video Updates',
    '_bx_videos_sbs_comments' => 'New Video Comments',
    '_bx_videos_sbs_rates' => 'New Video Votes',
	'_bx_videos_single' => 'Video',
	'_bx_videos_size' => 'Size',
	'_bx_videos_size_unit' => 'Kb',
	'_bx_videos_special' => 'Featured Videos',
    '_bx_videos_spy_added' => '<a href="{profile_link}">{profile_nick}</a> added a new video <a href="{entry_url}">{entry_caption}</a>',
    '_bx_videos_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">video</a> was commented by <a href="{profile_link}">{profile_nick}</a>',
    '_bx_videos_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">video</a> was rated by <a href="{profile_link}">{profile_nick}</a>',
	'_bx_videos_submit' => 'Submit',
	'_bx_videos_top' => 'Top Videos',
	'_bx_videos_top_menu_all' => 'All Videos',
    '_bx_videos_top_menu_album' => 'Video album',
    '_bx_videos_top_menu_albums' => 'Video albums',
	'_bx_videos_top_menu_calendar' => 'Calendar',
	'_bx_videos_top_menu_categories' => 'Categories',
    '_bx_videos_top_menu_category' => 'Category',
	'_bx_videos_top_menu_favorited' => 'My favorite videos',
	'_bx_videos_top_menu_featured' => 'Featured Videos',
	'_bx_videos_top_menu_home' => 'Videos home',
	'_bx_videos_top_menu_item' => 'Videos',
	'_bx_videos_top_menu_popular' => 'Popular Videos',
	'_bx_videos_top_menu_profile' => 'Profiles Videos',
    '_bx_videos_top_menu_rate' => 'Rater',
	'_bx_videos_top_menu_search' => 'Search',
	'_bx_videos_top_menu_tags' => 'Tags',
	'_bx_videos_top_menu_top' => 'Top Videos',
	'_bx_videos_undefined' => 'Undefined',
	'_bx_videos_emb_err' => 'Embedding video failed',
	'_bx_videos_upl_err' => 'Video upload failed (failed to accept information)',
	'_bx_videos_upl_file_err' => 'Video upload failed (Video error)',
	'_bx_videos_upl_succ' => 'Video was added successfully',
	'_bx_videos_upload' => 'Videos',
	'_bx_videos_val_descr_err' => 'Description can`t be empty',
	'_bx_videos_val_title_err' => 'Title can`t be empty',
	'_bx_videos_Video_block' => 'Profile Videos', 
	'_bx_videos_view' => 'View Video',
	'_bx_videos_view_alt_fav'  => 'Favorited',
	'_bx_videos_view_alt_view' => 'Viewed',
    '_bx_videos_wall_added_new' => 'added new',
    '_bx_videos_wall_video' => 'video',
    '_bx_videos_wall_video_private' => 'private video',
    '_sbs_txt_title_bx_videos' => 'Video subscriptions',
	'_mma_videos_add' => 'videos add',
	'_mma_videos_view' => 'videos view', 
	'_mma_videos_delete' => 'videos delete',
	'_mma_videos_download' => 'videos download',
	'_mma_videos_approve' => 'videos approve',
	'_mma_videos_edit' => 'videos edit',
	'_bx_videos_profile_videos' => 'Profile Videos',
);

?>
