#!/usr/bin/env php
<?php
define('ROOT_DIR',realpath(dirname(__FILE__).'/../../'));
define('APP_DIR',realpath(dirname(__FILE__).'/../'));
require('kernel.php');
$shell = new base_shell_loader;
$shell->run();