#!/bin/sh

BASEDIR='../../../..'
. $BASEDIR/config
. $BASEDIR/functions

DEPOT=$BASEDIR/$DEPOT

pkgname='jpeg'

extract $pkgname
#
getSrcdir $pkgname

prefix=$INSTDIR/php
mandir=$prefix/man/man1
[ -d $mandir ] || mkdir -p $mandir 
cmd="
./configure --prefix=$prefix --mandir=$mandir
"
echo $cmd > .log
pushd $srcdir > /dev/null
compile $cmd
make install-lib
popd > /dev/null
