<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Boonex Files';

$aLangContent = array(
	'_bx_files' => 'Files',
	'_bx_files_access_denied' => 'Access denied',
	'_bx_files_action_fave' => 'Add to Favorites',
	'_bx_files_action_unfave' => 'Drop from Favorites',
	'_bx_files_action_report' => 'Report',
	'_bx_files_action_share' => 'Share',
    '_bx_files_action_download' => 'Download',
	'_bx_files_actions' => 'Actions',
	'_bx_files_add' => 'Add file',
	'_bx_files_add_regular' => 'Regular',
	'_bx_files_add_info' => '<a href="{0}">Click here</a> to add more.',
	'_bx_files_add_objects' => 'Add files',
	'_bx_files_admin' => 'Administration',
	'_bx_files_admin_activate' => 'Activate',
	'_bx_files_admin_deactivate' => 'Deactivate',
	'_bx_files_admin_delete' => 'Delete',
	'_bx_files_admin_feature' => 'Make featured',
	'_bx_files_admin_main' => 'Main',
	'_bx_files_admin_settings' => 'Settings',
	'_bx_files_admin_unfeature' => 'Make unfeatured',
	'_bx_files_albums_add' => 'Add folder',
	'_bx_files_albums_admin' => 'Folders administration',
	'_bx_files_albums_disapproved' => 'My disapproved folders',
	'_bx_files_albums_my' => 'My folders',
	'_bx_files_albums_count_info' => 'You have {0} <a href="{1}">folders(s)</a>.',
    '_bx_files_albums_add_info' => '<a href="{0}">Click here</a> to create a new folder.',
    '_bx_files_albums_latest' => 'Folders',
	'_bx_files_album' => 'Folder',
    '_bx_files_album_add' => 'Add',
	'_bx_files_album_add_objects' => 'Add files',
	'_bx_files_album_delete' => 'Delete',
	'_bx_files_album_delete_confirm' => 'Confirm',
	'_bx_files_album_delete_error' => '{0} file(s) were left',
	'_bx_files_album_delete_success' => 'Folder was deleted successfully',
	'_bx_files_album_delete_warning' => 'Are you sure about deletion of entire folder and all contents?',
	'_bx_files_album_disapproved' => 'Disapproved',
	'_bx_files_album_edit' => 'Edit folder',
	'_bx_files_album_info' => 'Folder info',
	'_bx_files_album_main' => 'Main',
	'_bx_files_album_main_objects' => 'Main',
	'_bx_files_album_manage' => 'Manage',
	'_bx_files_album_manage_objects' => 'Manage files',
	'_bx_files_album_manage_objects_disapproved' => 'Disapproved',
	'_bx_files_album_manage_objects_pending' => 'Pending',
	'_bx_files_album_objects' => 'Files of this folder',
	'_bx_files_album_organize' => 'Organize',
	'_bx_files_album_organize_reverse' => 'Reverse',
	'_bx_files_album_save_success' => 'Folder info was saved successfully',
	'_bx_files_album_view' => 'Allow viewing of folder to',
	'_bx_files_albums' => 'File Folders',
	'_bx_files_alert_commented' => '{0} commented your file',
	'_bx_files_alert_rated' => 'File was commented',
	'_bx_files_all' => 'All files',
	'_bx_files_any' => 'Any',
	'_bx_files_approved' => 'Approved',
	'_bx_files_bcaption_all' => 'All tags',
	'_bx_files_browse' => 'Browse',
	'_bx_files_browse_by_album' => 'Browse files from folder "{0}"',
	'_bx_files_browse_by_tag' => 'Browse files by tag "{0}"',
	'_bx_files_browse_by_category' => 'Browse files by category "{0}"',
	'_bx_files_browse_by_owner' => 'Browse files from {0}',
    '_bx_files_caption_browse_by_day' => 'Browse files by day',
	'_bx_files_browse_file' => 'Select file',
    '_bx_files_categories_all' => 'All categories',
	'_bx_files_choose_uploader' => 'Choose uploader',
	'_bx_files_close' => 'Close',
	'_bx_files_comments' => 'Comments',
	'_bx_files_count_info' => 'You have {0} <a href="{1}">file(s)</a> in this folder.',
	'_bx_files_count_status_info' => 'You have {0} <a href="{1}">{2} file(s)</a> in this folder.',
	'_bx_files_couple_file_block' => 'Couple Files',
	'_bx_files_delete' => 'File was deleted',
	'_bx_files_delete_from_album' => 'Delete from folder',
	'_bx_files_delete_error' => 'File deleting error',
	'_bx_files_disapproved' => 'Disapproved',
	'_bx_files_distribute' => 'Terms of condition for files distribution',
    '_bx_files_download' => 'Download',
	'_bx_files_embed' => 'Embed',
	'_bx_files_Embed' => 'Flickr file link',
	'_bx_files_Embed_example' => 'Example: http://www.flickr.com/files/valentina_petrozziello/2939555818/',
	'_bx_files_fav_add' => 'File was added to favorite list',
	'_bx_files_fav_remove' => 'File was removed from favorite list',
	'_bx_files_favorited' => 'My favorite files',
	'_bx_files_featured' => 'Features files',
	'_bx_files_file_not_found' => 'File not found',
	'_bx_files_file_was_uploaded' => 'Your file was uploaded (id:{0}) by {1}',
	'_bx_files_forbidden' => 'Access is forbidden',
	'_bx_files_home' => 'Files home',
	'_bx_files_i_have_the_right_to_distribute' => 'I have the right to distribute these files',
	'_bx_files_info' => 'File info',
	'_bx_files_info_main' => 'Main file info',
	'_bx_files_latest' => 'Latest files from this user',
	'_bx_files_latest_file' => 'File of the day',
	'_bx_files_main' => 'Main',
	'_bx_files_menu_pending' => 'Pending',
	'_bx_files_menu_profile' => 'Files',
	'_bx_files_my' => 'My files',
	'_bx_files_msg_page_not_found' => 'Page not found',
	'_bx_files_no_file_for_rate' => 'No files for rate',
	'_bx_files_not_found' => 'File not found',
	'_bx_files_organize_objects' => 'Organize',
	'_bx_files_pending' => 'Pending',
	'_bx_files_file_block' => 'Profile Files', 
	'_bx_files_plural' => 'files',
	'_bx_files_preview' => 'Preview',
	'_bx_files_profile_album_name' => '{0}\'s files',
	'_bx_files_previous_rated' => 'Previous rated',
	'_bx_files_public' => 'Public files',
	'_bx_files_rate' => 'Rate',
	'_bx_files_rate_header' => 'Rate',
	'_bx_files_record' => 'Record',
	'_bx_files_regular' => 'Regular',
	'_bx_files_related' => 'Related files',
	'_bx_files_save_success' => 'File info was saved',
    '_bx_files_sbs_main' => 'File Updates',
    '_bx_files_sbs_comments' => 'New File Comments',
    '_bx_files_sbs_rates' => 'New File Votes',
	'_bx_files_single' => 'file',
	'_bx_files_size' => 'Size',
	'_bx_files_size_unit' => 'Kb',
	'_bx_files_special' => 'Featured files',
    '_bx_files_spy_added' => '<a href="{profile_link}">{profile_nick}</a> added a new file <a href="{entry_url}">{entry_caption}</a>',
    '_bx_files_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">file</a> was commented by <a href="{profile_link}">{profile_nick}</a>',
    '_bx_files_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{entry_url}">file</a> was rated by <a href="{profile_link}">{profile_nick}</a>',
	'_bx_files_submit' => 'Submit',
	'_bx_files_top' => 'Top files',
	'_bx_files_top_menu_albums' => 'File folders',
    '_bx_files_top_menu_album' => 'File folder',
	'_bx_files_top_menu_all' => 'All files',
	'_bx_files_top_menu_calendar' => 'Calendar',
	'_bx_files_top_menu_categories' => 'Categories',
	'_bx_files_top_menu_category' => 'Category',
	'_bx_files_top_menu_favorited' => 'My favorite files',
	'_bx_files_top_menu_featured' => 'Featured files',
	'_bx_files_top_menu_home' => 'Files home',
	'_bx_files_top_menu_item' => 'Files',
	'_bx_files_top_menu_popular' => 'Popular files',
	'_bx_files_top_menu_profile' => 'Profiles files',
	'_bx_files_top_menu_search' => 'Search',
	'_bx_files_top_menu_tags' => 'Tags',	
	'_bx_files_top_menu_top' => 'Top files',
	'_bx_files_undefined' => 'Undefined',
	'_bx_files_upl_err' => 'file upload failed (failed to accept information)',
	'_bx_files_upl_file_err' => 'file upload failed (file error)',
	'_bx_files_upl_succ' => 'file was uploaded successfully',
	'_bx_files_upload' => 'Files',
	'_bx_files_val_descr_err' => 'Description can`t be empty',
	'_bx_files_val_title_err' => 'Title can`t be empty',
	'_bx_files_view' => 'View file',
	'_bx_files_view_alt_fav'  => 'Favorited',
	'_bx_files_view_alt_view' => 'Viewed',
	'_bx_files_wall_added_new' => 'added new',
    '_bx_files_wall_file' => 'file',
    '_bx_files_wall_file_private' => 'private file',
    '_sbs_txt_title_bx_files' => 'File subscriptions',
	'_mma_files_add' => 'files add',
	'_mma_files_view' => 'files view', 
	'_mma_files_delete' => 'files delete',
	'_mma_files_download' => 'files download',
	'_mma_files_approve' => 'files approve',
	'_mma_files_edit' => 'files edit',
);

?>
