#!/bin/sh
svn update
gcc  -g -lssl libdatasafe.c  -fPIC -shared -o libdatasafe.so 
cp libdatasafe.so /usr/lib
gcc  -g -ldatasafe -L/usr/lib test_get_shopex_key.c -o test_get_shopex_key
gcc  -g -ldatasafe -L/usr/lib test_base64.c -o test_base64
gcc  -g -ldatasafe -L/usr/lib test_shopex_conf_rsa_encrypt.c -o test_shopex_conf_rsa_encrypt
gcc  -g -ldatasafe -L/usr/lib test_shopex_conf_rsa_decrypt.c -o test_shopex_conf_rsa_decrypt
gcc  -g -ldatasafe -L/usr/lib test_shopex_data_encrypt.c -o test_shopex_data_encrypt
gcc  -g -ldatasafe -L/usr/lib test_shopex_data_decrypt.c -o test_shopex_data_decrypt
gcc  -g -ldatasafe -L/usr/lib test_shopex_read_conf_file.c -o test_shopex_read_conf_file
gcc  -g -ldatasafe -L/usr/lib encrypt_config.c -o encrypt_config
gcc  -g -ldatasafe -L/usr/lib decrypt_config.c -o decrypt_config
gcc  -g -ldatasafe -L/usr/lib encrypt_user_privkey.c -o encrypt_user_privkey
gcc  -g -ldatasafe -L/usr/lib decrypt_user_privkey.c -o decrypt_user_privkey
gcc  -g -ldatasafe -L/usr/lib test_get_user_private_key_en.c -o test_get_user_private_key_en
